# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.CharField(choices=[('The beach', 'a'), ('An amusement park', 'b'), ('The dinner table', 'c'), ('I am not sure', 'd')], max_length=1, verbose_name='Where is the patient at the beginning of the story?')),
                ('Q2', models.CharField(choices=[('Vision problems', 'a'), ('Shortness of breath', 'b'), ('Headache', 'c'), ('Pain in her leg', 'd'), ('I am not sure', 'e')], max_length=1, verbose_name="What is the patient's concern?")),
                ('Q3', models.CharField(choices=[('reading glasses', 'a'), ('asthma medication', 'b'), ('cataract surgery', 'c'), ('a cast', 'd'), ('no procedure', 'e'), ('I am not sure', 'f')], max_length=1, verbose_name='What does the doctor suggest for the patient?')),
                ('Q4', models.CharField(choices=[('nausea  and vomitting', 'a'), ('infection, bleeding, loss of vision, double vision, after-cataract', 'b'), ('no risk', 'c'), ('I am not sure', 'd')], max_length=1, verbose_name='What are the risks of the surgery that the doctor explains to the patient?')),
                ('Q5', models.CharField(choices=[('Yes, the minor risks of complications outweighs the risk of the cataract getting worse and requiring a more complicated surgery with more risks later on.', 'a'), ('No, the minor risks of complications does not outweigh the minor risk of the cataract getting worse and requiring a more complicated surgery with more risks later on.', 'b'), ('No, the doctor does not want his patient to receive the surgery', 'c'), ('I am not sure', 'd')], max_length=1, verbose_name='Do the risks of receiving the cataract surgery outweigh the risks of not receiving the surgery?')),
                ('Q6', models.CharField(choices=[('Her cataract will heal on its own', 'a'), ('Her cataract may get worse', 'b'), ('I am not sure', 'c')], max_length=1, verbose_name='If the patient does not receive the surgery...')),
                ('Q7', models.CharField(choices=[('Yes', 'y'), ('No', 'n')], max_length=1, verbose_name='In your opinion, should the patient receive the surgery?')),
                ('Q8', models.CharField(max_length=400, verbose_name='Why?')),
            ],
        ),
    ]
