# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Q1',
            field=models.CharField(choices=[('a', 'The beach'), ('b', 'An amusement park'), ('c', 'The dinner table'), ('d', 'I am not sure')], max_length=1, verbose_name='Where is the patient at the beginning of the story?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q2',
            field=models.CharField(choices=[('a', 'Vision problems'), ('b', 'Shortness of breath'), ('c', 'Headache'), ('d', 'Pain in her leg'), ('e', 'I am not sure')], max_length=1, verbose_name="What is the patient's concern?"),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q3',
            field=models.CharField(choices=[('a', 'reading glasses'), ('b', 'asthma medication'), ('c', 'cataract surgery'), ('d', 'a cast'), ('e', 'no procedure'), ('f', 'I am not sure')], max_length=1, verbose_name='What does the doctor suggest for the patient?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q4',
            field=models.CharField(choices=[('a', 'nausea  and vomitting'), ('b', 'infection, bleeding, loss of vision, double vision, after-cataract'), ('c', 'no risk'), ('d', 'I am not sure')], max_length=1, verbose_name='What are the risks of the surgery that the doctor explains to the patient?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q5',
            field=models.CharField(choices=[('a', 'Yes, the minor risks of complications outweighs the risk of the cataract getting worse and requiring a more complicated surgery with more risks later on.'), ('b', 'No, the minor risks of complications does not outweigh the minor risk of the cataract getting worse and requiring a more complicated surgery with more risks later on.'), ('c', 'No, the doctor does not want his patient to receive the surgery'), ('d', 'I am not sure')], max_length=1, verbose_name='Do the risks of receiving the cataract surgery outweigh the risks of not receiving the surgery?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q6',
            field=models.CharField(choices=[('a', 'Her cataract will heal on its own'), ('b', 'Her cataract may get worse'), ('c', 'I am not sure')], max_length=1, verbose_name='If the patient does not receive the surgery...'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q7',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, verbose_name='In your opinion, should the patient receive the surgery?'),
        ),
    ]
