# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0002_auto_20170305_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('healthcardNumber', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Health Card Number')),
                ('score', models.FloatField(verbose_name='Capacity score')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q1',
            field=models.IntegerField(choices=[(0, 'The beach'), (0, 'An amusement park'), (1, 'The dinner table'), (0, 'I am not sure')], verbose_name='Where is the patient at the beginning of the story?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q2',
            field=models.IntegerField(choices=[(1, 'Vision problems'), (0, 'Shortness of breath'), (0, 'Headache'), (0, 'Pain in her leg'), (0, 'I am not sure')], verbose_name="What is the patient's concern?"),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q3',
            field=models.IntegerField(choices=[(0, 'reading glasses'), (0, 'asthma medication'), (1, 'cataract surgery'), (0, 'a cast'), (0, 'no procedure'), (0, 'I am not sure')], verbose_name='What does the doctor suggest for the patient?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q4',
            field=models.IntegerField(choices=[(0, 'nausea  and vomitting'), (1, 'infection, bleeding, loss of vision, double vision, after-cataract'), (0, 'no risk'), (0, 'I am not sure')], verbose_name='What are the risks of the surgery that the doctor explains to the patient?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q5',
            field=models.IntegerField(choices=[(1, 'Yes, the minor risks of complications outweighs the risk of the cataract getting worse and requiring a more complicated surgery with more risks later on.'), (0, 'No, the minor risks of complications does not outweigh the minor risk of the cataract getting worse and requiring a more complicated surgery with more risks later on.'), (0, 'No, the doctor does not want his patient to receive the surgery'), (0, 'I am not sure')], verbose_name='Do the risks of receiving the cataract surgery outweigh the risks of not receiving the surgery?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q6',
            field=models.IntegerField(choices=[(0, 'Her cataract will heal on its own'), (1, 'Her cataract may get worse'), (0, 'I am not sure')], verbose_name='If the patient does not receive the surgery...'),
        ),
    ]
