# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20170305_1423'),
        ('Patient', '0002_auto_20170305_0244'),
    ]

    operations = [
    ]
