# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20170305_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.FloatField(null=True, verbose_name='Capacity score'),
        ),
    ]
