# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_merge_20170305_1502'),
        ('Patient', '0005_questions_profile'),
    ]

    operations = [
    ]
