# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20170305_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isResearcher',
            field=models.BooleanField(default=False, verbose_name='Researcher?'),
            preserve_default=False,
        ),
    ]
