# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20170305_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isResearcher',
            field=models.BooleanField(default=False, verbose_name='Researcher?'),
        ),
    ]
